# -*- coding: utf-8 -*-
"""VarunNair_programming_supplement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1df5ZSsUYQ91SlMUWZuJRM0zMCg7V0Sd6

**Spotify Chart Longevity & Ranking Dynamics (2017–2022)**

**Objective:** quantify (1) how peak rank relates to longevity and (2) how concentrated chart presence is across artists using 2,191 daily Spotify chart files.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import zipfile
import re

# Extract zip file we got from Kaggle
zip_path = Path("archive.zip")
data_dir = Path("data")

if zip_path.exists():
    data_dir.mkdir(exist_ok=True)
    with zipfile.ZipFile(zip_path, "r") as z:
        z.extractall(data_dir)

daily_dir = Path("data/daily") #Locate all daily Spotify chart CSV files (2017–2022)
daily_files = sorted(daily_dir.rglob("*.csv"))
#The dataset contains one CSV per day.
#We search the /data/daily directory recursively and collect all .csv files into a list.
def extract_date_from_path(p: Path) -> pd.Timestamp:
    s = re.sub(r"[_/]", "-", p.stem)
    dt = pd.to_datetime(s, format="%m-%d-%Y", errors="coerce")
    if pd.isna(dt):
        dt = pd.to_datetime(s, format="%Y-%m-%d", errors="coerce")
    return dt

dfs = [] # Reading each daily file and attaching its corresponding date
for p in daily_files:
    df = pd.read_csv(p)
    df["date"] = extract_date_from_path(p)
    dfs.append(df)

daily = pd.concat(dfs, ignore_index=True)

print("Daily files:", len(daily_files))
print("Combined rows:", len(daily))

# Standardize column names
# Removing extra whitespace, converting to lowercase, and replacing spaces with underscores.
daily.columns = (
    daily.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_", regex=False)
)
# Some Kaggle exports label columns inconsistently so we rename for clarity and consistency
daily = daily.rename(columns={"singer(s)": "artist", "stream": "streams"})
# Clean numeric fields (streams)
daily["streams"] = (
    daily["streams"].astype(str)
    .str.replace(".", "", regex=False)
    .str.replace(",", "", regex=False)
)
daily["streams"] = pd.to_numeric(daily["streams"], errors="coerce")
# Ensuring proper datetime type
daily["date"] = pd.to_datetime(daily["date"], errors="coerce")
# Constructing unique track identifier
daily["track_id"] = (
    daily["track"].astype(str).str.strip()
    + " — "
    + daily["artist"].astype(str).str.strip()
)

longevity = ( # Track-level longevity metrics
    daily.sort_values(["track_id", "date"])
    .groupby("track_id", as_index=False)
    .agg(
        artist=("artist", "first"),
        track=("track", "first"),
        days_on_chart=("date", "count"),
        first_day=("date", "min"),
        last_day=("date", "max"),
        peak_rank=("rank", "min"),
        avg_rank=("rank", "mean"),
    )
)
# Computing calendar run length (inclusive of first and last day)
longevity["run_length_days"] = (
    longevity["last_day"] - longevity["first_day"]
).dt.days + 1

print("Unique tracks:", longevity["track_id"].nunique())

# Relationship between peak performance and longevity
# Negative correlation means: better peak rank tends to be associated with more days on the chart.
correlation = longevity["peak_rank"].corr(longevity["days_on_chart"])
print("Correlation (peak_rank vs days_on_chart):", round(correlation, 3))

artist_stats = (
    longevity.groupby("artist", as_index=False)
    .agg(total_chart_days=("days_on_chart", "sum"))
)

artist_stats_sorted = artist_stats.sort_values(
    "total_chart_days", ascending=False
)

top_10_cut = int(len(artist_stats_sorted) * 0.10)
share_top_10 = (
    artist_stats_sorted.head(top_10_cut)["total_chart_days"].sum()
    / artist_stats_sorted["total_chart_days"].sum()
)

print("Top 10% share of total chart days:", round(share_top_10, 2))

#Gini coefficient measures inequality in total chart days across artists.
def gini(x):
    x = np.asarray(x, dtype=float)
    x = x[np.isfinite(x)]
    if x.size == 0:
        return np.nan
    if np.min(x) < 0:
        x = x - np.min(x)
    x = np.sort(x) + 1e-9
    n = x.size
    idx = np.arange(1, n + 1)
    return (np.sum((2 * idx - n - 1) * x)) / (n * np.sum(x))

g = gini(artist_stats["total_chart_days"])
print("Gini coefficient:", round(g, 3))

# Lorenz curve
values = np.sort(artist_stats["total_chart_days"].values)
cum = np.cumsum(values) / np.sum(values)
cum_artists = np.arange(1, len(values) + 1) / len(values)

plt.figure(figsize=(4, 2.6))
plt.tight_layout(pad=0.3)
plt.plot(cum_artists, cum)
plt.plot([0, 1], [0, 1], linestyle="--")
plt.title("Lorenz Curve")
plt.tight_layout()
plt.show()